# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS ACM PCA controller is a service controller for managing ACM PCA resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon ACM PCA
description: |-
  Manage Amazon ACM PCA resources in AWS from within your Kubernetes cluster.


  **About Amazon ACM PCA**


  AWS Private CA enables creation of private certificate authority (CA) hierarchies, including root and subordinate CAs, without the investment and maintenance costs of operating an on-premises CA. 
  Your private CAs can issue end-entity X.509 certificates useful in scenarios including:
  
   - Creating encrypted TLS communication channels
  
   - Authenticating users, computers, API endpoints, and IoT devices
  
   - Cryptographically signing code
  
   - Implementing Online Certificate Status Protocol (OCSP) for obtaining certificate revocation status


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.


  **Pre-Installation Steps**


  Please follow the following link: [Red Hat OpenShift](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/)
samples:
- kind: CertificateAuthority
  spec: '{}'
maintainers:
- name: "acmpca maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon ACM PCA Developer Resources
  url: https://aws.amazon.com/private-ca/resources
